Questão 1 - Fórmulas da Soma de inteiros elevado a m 
Onde temos as seguintes fórmulas:
m = 1 -> n(n-1)/2
m = 2 -> n(n-1)(2n+1)/6
m = 3 -> n²(n-1)²/4
Então a saída tem que ser uma fórmula dependendo do valor de m.

In [1]:
import sympy as sp

def faulhaber_formula(m):
    n = sp.Symbol('n', integer=True)
    sum_formula = 0
    
    for k in range(m + 1):
        bernoulli_term = sp.bernoulli(k)
        term = (bernoulli_term * sp.binomial(m + 1, k) * n**(m + 1 - k)) / (m + 1)
        sum_formula += term
    
    return sp.simplify(sum_formula)

# Exemplo de uso
m = 1
sp.pretty_print(faulhaber_formula(m))
print("\n")
m = 2
sp.pretty_print(faulhaber_formula(m))
print("\n")
m = 3
sp.pretty_print(faulhaber_formula(m))

n⋅(n + 1)
─────────
    2    


  ⎛   2          ⎞
n⋅⎝2⋅n  + 3⋅n + 1⎠
──────────────────
        6         


 2 ⎛ 2          ⎞
n ⋅⎝n  + 2⋅n + 1⎠
─────────────────
        4        


Questão 2 - Matriz da eletrônica Digital  
A matriz que comparece na análise de circuitos em eletronica digital  a vista a seguir:   
Aij = 1, se i - 1 / 2^(N - j) é ímpar; 0, se i - 1 / 2^(N - j) é par.  
Acima temos uma fórmula que gera a matriz, N é o número de variáveis lógicas (na entrada do circuito). 

In [1]:
import numpy as np
from math import floor

def EXPORT_MED(n):
    m = np.zeros((2**n, n), dtype=int) #Cria a matriz cheia de zeros
    
    for i in range(1, 2**n + 1): #linha e tem que ser + 1 pois não conta o último valor 
        for j in range(1, n + 1): #coluna e tem que ser + 1 pois não conta o último valor
            if floor((i-1) / 2**(n-j)) % 2 == 0:
                m[i-1, j-1] = 0
            else:
                m[i-1, j-1] = 1
    
    return print(m)

# Exemplo de uso igual do pdf
n = 3
EXPORT_MED(n)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


Numpy: Usei a biblioteca numpy para criar e manipular a matriz M, que é inicializada com zeros.  
Usa o [i-1] e [j-1] pois em python os arrays começam em 0. Então é necessário para usar o índice correto.

Questão 3 - Matriz de Combinações  
A conhecida fórmula da análise combinatória:  
(m,r) = m!/(m-r)!r!  
nos diz quantas são as combinações de m objetos tomados r a r; no entanto, ela não diz como encontrar as tais combinações A seguir damos uma fórmula que cumpre   essa finalidade.  
A matriz de combinações e a fórmula geratriz são vistas a seguir:  
Aij = 1, se i / 2^j é ímpar; 0, se i / 2^j é par.   

In [2]:
import numpy as np
from math import floor

def MATRIZ_COMBINA(n):
    m = np.zeros((2**n, n), dtype=int) #Cria a matriz cheia de zeros com dimensão 2^n x n
    
    for i in range(2**n): #linha - como na fórmula passada tinha 2^n-1, mas no python já exclui o último termo, logo apenas colocar 2^n e equivale a 2^n-1 da fórmula
        for j in range(n): #coluna - como na fórmula passada tinha n-1, mas no python já exclui o último termo, logo apenas colocar n e equivale a n-1 da fórmula
            if floor(i / 2**j) % 2 == 0:
                m[i, j] = 0
            else:
                m[i, j] = 1
    
    return print(m)

# Exemplo igual do pdf
n = 4
MATRIZ_COMBINA(n)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 1 1 0]
 [0 0 0 1]
 [1 0 0 1]
 [0 1 0 1]
 [1 1 0 1]
 [0 0 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 1 1]]


Referências:
Questão 1 - 
1 + 2 + 3 + ... + n = n(n-1)/2
1² + 2² + 3² + ... + n² = n(n-1)(2n+1)/6
1³ + 2³ + 3³ + ... + n³ = n²(n-1)²/4

Questão 2 - Matriz da eletrônica Digital
EXPORT MED(N)
BEGIN LOCAL M; M:=[[0]];
	FOR I FROM 1 TO 2^N DO
	    FOR j FROM 1 TO N DO
       IF   FLOOR((I-1)/2^(N-J)) MOD 2 == 0
       THEN M(I,J):=0
       ELSE M(I,J):=1
       END;
            END;
	END;
END;

Questão 3 - Matriz de Combinações
EXPORT MATRIZ_COMBINA(N)
BEGIN LOCAL M; M:=[[0]];
	FOR I FROM 0 TO 2^N-1 DO
	    FOR j FROM 0 TO N-1 DO
       IF   FLOOR((I/2^J)) MOD 2 == 0
       THEN M(I+1,J+1):=0
       ELSE M(I+1,J+1):=1
       END;
            END;
	END;
END;